### PR TITLE
Update, rename from validates_timeliness.en.yml to russian

### PR DESCRIPTION
**Pull request by ansarbek**
Russian version - validates_timeliness.ru.yml

### CODE REVIEW

**Comment by FiloSpaTeam** [comment]
Can you translate to a new file and don't overwrite english file? :+1:

**Comment by ansarbek** [comment]
I am sorry, this is my first commit :(

**Comment by FiloSpaTeam** [comment]
No problem :D i'm very happy that you liked the project. As you can see it's a very interesting software for project management and actually i'm trying to show and use in my company :+1: 

Are you a Rails developer?

**Comment by ansarbek** [comment]
Yeah, your project is very interesting, wish you success!
I am just at the beginning of the Rails,, trying to develop one app for environmnetal emission calculations

**Comment by FiloSpaTeam** [comment]
I'm very happy, you can contribute and share what you think about. You can do what you feel, i want to have a good team that can share my benefits.
As you can see the project is workload based and we can see how many tasks we have done :+1: 

If you need help don't hesitate. 

PS: Use the software itself to handle tasks so we can work together! :+1: :+1: :+1:

**Pull request merged**
